name: Continuous Deployment

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH and deploy app
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd ~/forumapi
          git pull origin main
          npm install
          npm run migrate up
          pm2 restart forumapi
        host: ${{ secrets.SSH_HOST }}
        user: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}